version: '3.4'

services:
  # mongo:
  #   image: mongo:latest
  #   hostname: mongodb
  #   container_name: mongodb
  #   restart: unless-stopped
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./mongodata:/data/db

  birdnames:
    image: "jdevil/birdnames:latest"
    # depends_on:
    #   - mongo
    ports:
      - "80:80"
      # - "27017:27017"
    container_name: "birdnames"
    command: "dotnet BirdNames.Blazor.dll"
    restart: unless-stopped
    # command: sh -c "mongod & exec dotnet BirdNames.Blazor.dll"
    # volumes:
    #   - ./mongodata:/data/db
    # command: "tail -f"